# Generated by Django 4.2 on 2023-04-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_monitored',
            field=models.BooleanField(default=False),
        ),
    ]
