# Generated by Django 4.2 on 2023-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_manager', '0002_server_is_monitored'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='health_monitored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='passwordless',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
